# Generated by Django 4.0.4 on 2022-06-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
