# Generated by Django 4.0.4 on 2022-06-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
