# Generated by Django 4.0.4 on 2022-06-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
    ]
