# Generated by Django 4.0.4 on 2022-06-28 21:56

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField(max_length=50)),
                ('subtitulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
