# Generated by Django 4.0.4 on 2022-06-28 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0009_alter_blog_fecha_alter_blog_imagen_alter_blog_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='imagenes'),
            preserve_default=False,
        ),
    ]
