# Generated by Django 4.0.4 on 2022-06-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0010_alter_blog_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=100)),
            ],
        ),
    ]
