# Generated by Django 4.0.4 on 2022-06-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0012_mensajes_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='autor',
        ),
    ]
