# Generated by Django 4.0.4 on 2022-06-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0014_mensajes_autor_mensajes_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='fecha',
        ),
    ]
